# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296c672a4ebcd068031985250b3466a93a738f9f1b0d2023c3b5157865b316d12821c314c731d36a42a97fbc7beec4accf6e3893044517d910fb6eb118c9f86b

test:
  secret_key_base: 74e51239dcdacd2cbf96e8b49e395addfa38fe6423ebf29b7c8a8eae96896d42bd45baa0c952abf8a4cc4c973e0e796e2ff9af3ce099f1b4301ac20d4c296c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
